---
# used for running pre-commit checks
name: pre-commit checks

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  run_pre_commit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - uses: pre-commit/action@v3.0.1
