# used for running pytest tests
name: pytest tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pytest_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Setup poetry
        shell: bash
        run: |
          python -m pip install poetry
      - name: Run pytest
        run: |
          poetry run pytest
